pathways:
  default: workshop

  paths:
    workshop:
      title: "Docker: Sieťovanie, porty a úložisko"
      duration: 60m

      steps:
      - 00-workshop-overview
      - 01-port-mapping
      - 02-volumes-and-data
      - 03-container-networking
      - 04-cleanup
      - 99-workshop-summary

modules:
- name: 00-workshop-overview
  title: Prehľad workshopu

- name: 01-port-mapping
  title: Mapovanie portov a sprístupnenie služieb

- name: 02-volumes-and-data
  title: Volumes a perzistentné dáta

- name: 03-container-networking
  title: Sieťovanie kontajnerov

- name: 04-cleanup
  title: Upratovanie a osvedčené postupy

- name: 99-workshop-summary
  title: Zhrnutie workshopu
