pathways:
  default: workshop

  paths:
    workshop:
      title: "Úvod do Docker Compose"
      duration: 45m

      steps:
      - 00-workshop-overview
      - 01-compose-basics
      - 02-first-compose-file
      - 03-multi-container-apps
      - 04-compose-commands
      - 05-environment-and-volumes
      - 06-scaling-and-profiles
      - 99-workshop-summary

modules:
- name: 00-workshop-overview
  title: Prehľad workshopu

- name: 01-compose-basics
  title: Čo je Docker Compose?

- name: 02-first-compose-file
  title: Váš prvý Compose súbor

- name: 03-multi-container-apps
  title: Viackontajnerové aplikácie

- name: 04-compose-commands
  title: Základné Compose príkazy

- name: 05-environment-and-volumes
  title: Environment, volumes a networking

- name: 06-scaling-and-profiles
  title: Škálovanie a profiles

- name: 99-workshop-summary
  title: Zhrnutie workshopu
