pathways:
  default: workshop

  paths:
    workshop:
      title: "Kubernetes: Services, Secrets a úložisko"
      duration: 105m

      steps:
      - 00-workshop-overview
      - 01-labels-selectors-namespaces
      - 02-networking-basics
      - 03-services
      - 04-secrets
      - 05-persistent-storage
      - 06-probes
      - 07-jobs-cronjobs
      - 99-workshop-summary

modules:
- name: 00-workshop-overview
  title: Prehľad workshopu

- name: 01-labels-selectors-namespaces
  title: Labels, selektory a namespaces

- name: 02-networking-basics
  title: Sieťovanie Podov a DNS

- name: 03-services
  title: Services

- name: 04-secrets
  title: Secrets

- name: 05-persistent-storage
  title: Trvalé úložisko

- name: 06-probes
  title: Liveness a readiness probes

- name: 07-jobs-cronjobs
  title: Jobs a CronJobs

- name: 99-workshop-summary
  title: Zhrnutie workshopu
