apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: grafana-intro-docker
spec:
  title: "Grafana with Docker - Quick Start"
  description: "Learn how to run Grafana using official Docker images and Docker Compose."
  url: https://github.com/tbocinec/educates-labs
  
  publish:
    image: "$(image_repository)/grafana-intro-docker-files:$(workshop_version)"
    files:
    - directory:
        path: .
      includePaths:
      - /workshop/**
      - /README.md

  workshop:
    files:
    - image:
        url: "$(image_repository)/grafana-intro-docker-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /README.md

  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: default
      editor:
        enabled: false
      docker:
        enabled: true
        socket:
          enabled: true
      console:
        enabled: false
    ingresses:
    - name: grafana
      port: 3000
    dashboards:
    - name: Grafana
      url: "$(ingress_protocol)://$(session_namespace)-grafana.$(ingress_domain)"
