pathways:
  default: workshop

  paths:
    workshop:
      title: "Kubernetes: Troubleshooting"
      duration: 60m

      steps:
      - 00-workshop-overview
      - 01-debugging-method
      - 02-pod-wont-start
      - 03-pod-keeps-dying
      - 04-pod-stays-pending
      - 05-app-unreachable
      - 99-workshop-summary

modules:
- name: 00-workshop-overview
  title: Prehľad workshopu

- name: 01-debugging-method
  title: Metóda, ktorá funguje

- name: 02-pod-wont-start
  title: Pod nikdy nenaštartuje

- name: 03-pod-keeps-dying
  title: Pod naštartuje a zomrie

- name: 04-pod-stays-pending
  title: Pod ostáva v Pending

- name: 05-app-unreachable
  title: Aplikácia je nedostupná

- name: 99-workshop-summary
  title: Zhrnutie workshopu
