-- Create database and tables (data will be generated by script)
CREATE DATABASE IF NOT EXISTS workshop;

USE workshop;

-- Sales data table
CREATE TABLE IF NOT EXISTS sales (
    timestamp DateTime,
    product String,
    region String,
    amount Decimal(10,2),
    quantity UInt32,
    customer_id UInt32
) ENGINE = MergeTree()
ORDER BY timestamp;

-- Website analytics table
CREATE TABLE IF NOT EXISTS website_stats (
    timestamp DateTime,
    page_url String,
    user_agent String,
    response_time_ms UInt32,
    status_code UInt16,
    user_country String
) ENGINE = MergeTree()
ORDER BY timestamp;

-- Performance metrics table
CREATE TABLE IF NOT EXISTS performance (
    timestamp DateTime,
    server_name String,
    cpu_usage Float32,
    memory_usage_mb UInt32,
    disk_usage_percent Float32,
    network_io_mb Float32
) ENGINE = MergeTree()
ORDER BY timestamp;

-- Tables created, data will be generated by generate-business-data.sh script