FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-venv
RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/pip install flask==3.1.0

COPY app.py /app/app.py

CMD ["/opt/venv/bin/python", "/app/app.py"]
