apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: kafka-intro
spec:
  title: "Kafka Intro with Docker"
  description: "Jednoduchý workshop: spustenie Apache Kafka cez Docker Compose, vytvorenie topicu a posielanie/čítanie správ."
  url: https://github.com/tbocinec/educates-labs
  publish:
    image: "$(image_repository)/kafka-intro-files:$(workshop_version)"
    files:
    - directory:
        path: .
      includePaths:
      - /workshop/**
      - /README.md

  workshop:
    files:
    - image:
        url: "$(image_repository)/kafka-intro-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /README.md

  session:
    namespaces:
      budget: x-large

    applications:
      terminal:
        enabled: true
      editor:
        enabled: true
      docker:
        enabled: true
        socket:
          enabled: true