pathways:
  default: workshop

  paths:
    workshop:
      title: "Úvod do Dockeru"
      duration: 60m

      steps:
      - 00-workshop-overview
      - 01-docker-basics
      - 02-running-first-container
      - 03-container-lifecycle
      - 04-executing-commands
      - 05-container-logs
      - 06-environment-variables
      - 07-docker-images
      - 99-workshop-summary

modules:
- name: 00-workshop-overview
  title: Prehľad workshopu

- name: 01-docker-basics
  title: Základy a architektúra Dockeru

- name: 02-running-first-container
  title: Spustenie vášho prvého containera

- name: 03-container-lifecycle
  title: Správa životného cyklu containera

- name: 04-executing-commands
  title: Vykonávanie príkazov vo vnútri containers

- name: 05-container-logs
  title: Práca s logmi containers

- name: 06-environment-variables
  title: Environment variables a konfigurácia

- name: 07-docker-images
  title: Skúmanie Docker images

- name: 99-workshop-summary
  title: Zhrnutie workshopu
