services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"

  cache:
    image: redis:7

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
      POSTGRES_DB: demo
