pathways:
  default: workshop

  paths:
    workshop:
      title: "Vytváranie Docker images pomocou Dockerfile"
      duration: 60m

      steps:
      - 00-workshop-overview
      - 01-dockerfile-basics
      - 02-first-image
      - 03-image-layers
      - 04-more-instructions
      - 05-best-practices
      - 06-multistage-builds
      - 99-workshop-summary

modules:
- name: 00-workshop-overview
  title: Prehľad workshopu

- name: 01-dockerfile-basics
  title: Základy Dockerfile

- name: 02-first-image
  title: Vytvorenie prvého image

- name: 03-image-layers
  title: Pochopenie vrstiev image (layers)

- name: 04-more-instructions
  title: Podrobný pohľad na inštrukcie Dockerfile

- name: 05-best-practices
  title: Osvedčené postupy

- name: 06-multistage-builds
  title: Multi-stage builds

- name: 99-workshop-summary
  title: Zhrnutie workshopu
